name: Build and Deploy
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
          - run : yarn
          - run : yarn build
          - run : git config user.name github-actions
          - run : git config user.email github-actions@github.com
          - run : git --work-tree build add --all
          - run : git commit -m "Automatic Build and Deploy run by GitHub Actions"
          - run : git push origin HEAD:gh-pages --force
